language: ruby
cache: bundler
rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
env:
- COVERALLS_SILENT=true
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

install:
  - "bundle install --jobs=3 --retry=3 --path=vendor/bundle"
  - "mkdir -p test/dummy/tmp/cache"
  - "mkdir -p test/dummy/tmp/non_default_location"

gemfile:
  - gemfiles/rails4_0.gemfile
  - gemfiles/rails4_1.gemfile
  - gemfiles/rails4_2.gemfile
  - gemfiles/rails5_0.gemfile
  - gemfiles/rails5_1.gemfile
  - gemfiles/rails5_2.gemfile
  - gemfiles/rails6_0.gemfile

matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails5_0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails5_1.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails5_2.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails6_0.gemfile
    - rvm: 2.2.9
      gemfile: gemfiles/rails6_0.gemfile
    - rvm: 2.3.6
      gemfile: gemfiles/rails6_0.gemfile
    # rails <=4.1 segfaults with ruby 2.4+
    - rvm: 2.4.3
      gemfile: gemfiles/rails4_0.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails4_1.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails6_0.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails4_0.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails4_1.gemfile

jobs:
  include:
    - stage: Lint
      rvm: 2.6.4
      script: bundle exec rubocop
